name: 🐞 Bug report
description: Report a bug in Miru
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Brief summary
      description: Please describe what went wrong.
    validations:
      required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce
      description: Please provide steps to reproduce this issue. Screenshots or videos can be very helpful.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: false

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false

  - type: input
    id: miru-version
    attributes:
      label: Miru version
      description: You can find your Miru version in **Settings**.
      placeholder: 'Example: "1.6.7"'
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Android
        - Windows
        - Linux
        - macOS
        - iOS
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device / OS Version
      description: List your device model and OS version.
      placeholder: 'Example: "Google Pixel 8 (Android 14)" or "Windows 11"'
    validations:
      required: false

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      options:
        - label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
          required: true
        - label: If this is an issue with an extension, I should open an issue in the [extension repository](https://github.com/miru-project/repo/issues/new) instead.
          required: true
