buildscript {
    ext.kotlin_version = '2.0.0'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

subprojects {
    def setNamespace = { project ->
        if (project.hasProperty('android')) {
            if (project.android.namespace == null) {
                def manifestFile = project.file("${project.projectDir}/src/main/AndroidManifest.xml")
                if (manifestFile.exists()) {
                    def parsedManifest = new groovy.xml.XmlParser().parse(manifestFile)
                    def packageName = parsedManifest.@package
                    if (packageName) {
                        project.android.namespace = packageName
                    }
                }
            }
        }
    }
    if (project.state.executed) {
        setNamespace(project)
    } else {
        project.afterEvaluate { setNamespace(it) }
    }
}
